# ----------------------------
# build from source
# ----------------------------
    FROM node:18 AS builder

    WORKDIR /app
    
    COPY package*.json ./
    RUN npm install
    
    COPY . .
    RUN npm run build
    
    # ----------------------------
    # run with nginx
    # ----------------------------
    FROM nginx:alpine

    WORKDIR /usr/share/nginx/html

    RUN rm -rf ./*
    COPY --from=builder /app/dist .

    ENTRYPOINT [ "nginx", "-g", "daemon off"; ]