version: "3.3"

services:
  front:
    build: .
    image: rafenex/pedidosfront:1.0
    container_name: pedidofront
    restart: always
    networks:
      - compose-bridge
    ports:
      - "80:80"

networks:
  compose-bridge:
    external: true
