version: "3.3"

networks:
  compose-bridge:
    external: true

services:
  front:
    build:
      context: .
    restart: always
    image: rafenex/pedidosfront:1.0
    container_name: pedidofront
    networks:
      - compose-bridge
    ports:
      - 127.0.0.1:8080:8080
