version: '3.3'

services:
  build:
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./API:/app
    command: mvn clean package

  pedidoapi:
    build:
      context: ./API
      dockerfile: Dockerfile
    restart: always
    image: rafenex/pedidosback:1.0
    container_name: pedidoback
    networks:
      - compose-bridge
    ports:
      - 8080:8080
    environment: 
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/pedidosank?allowPublicKeyRetrieval=true   
    volumes:
      - pedidoapi_data:/app/data

networks:
  compose-bridge:
    driver: bridge

volumes:
  pedidoapi_data:
