version: "3.3"

services:
  pedidoapi:
    build:
      context: .
      dockerfile: ./backend/API/Dockerfile
    restart: always
    image: rafenex/pedidosback:1.0
    container_name: pedidoback
    networks:
      - compose-bridge
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/pedidosank?allowPublicKeyRetrieval=true
    volumes:
      - pedidoapi_data:/app/data

  mysqldb:
    restart: always
    image: mysql:8.0
    container_name: pedidodb
    networks:
      - compose-bridge
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: pedidosank
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  front:
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
    restart: always
    image: rafenex/pedidosfront:1.0
    container_name: pedidofront
    networks:
      - compose-bridge
    ports:
      - 8080:8080

networks:
  compose-bridge:
    driver: bridge

volumes:
  pedidoapi_data:
  mysql_data:
