version: '3.3'

services:
  frontend:
    restart: always
    build: ./Front
    container_name: pedidofront
    networks:
      - compose-bridge
    ports:
      - 4200:4200
    volumes:
      - frontend_data:/app/data

networks:
  compose-bridge:
    driver: bridge

volumes:
  frontend_data: