version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlank
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidosank
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pedidos-network

  app:
    build: ./backend
    container_name: pedidos-container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlank:3306/pedidosank?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - pedidos-network

  frontend:
    image: nginx:alpine
    container_name: angular-app
    ports:
      - "4200:80"  # você acessa em http://localhost:4200
    volumes:
      - ./dist/nome-do-seu-projeto:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
networks:
  pedidos-network:
    driver: bridge
