version: "3.3"

services:

  mysqldb:
    restart: always
    image: mysql:8.0
    container_name: pedidodb
    networks:
      - compose-bridge
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: pedidosank
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  pedidoapi:
    build:
      context: ./backend/API
    restart: always
    image: rafenex/pedidosback:1.0
    container_name: pedidoback
    networks:
      - compose-bridge
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/pedidosank?allowPublicKeyRetrieval=true
    volumes:
      - pedidoapi_data:/app/data
    depends_on:
      - mysqldb  

  front:
    build:
      context: ./frontend
    restart: always
    image: rafenex/pedidosfront:1.0
    container_name: pedidofront
    networks:
      - compose-bridge
    ports:
      - "127.0.0.1:80:80"

    depends_on:
      - pedidoapi

networks:
  compose-bridge:
    driver: bridge

volumes:
  pedidoapi_data:
  mysql_data:
