version: "3.3"

services:
  front:
    build:
      context: ./frontend
    restart: always
    image: rafenex/pedidosfront:1.0
    container_name: pedidofront
    networks:
      - compose-bridge
    ports:
      - "127.0.0.1:80:80"

networks:
  compose-bridge:
    driver: bridge

