version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidosank
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - pedidos-network
    

  backend:
    image: openjdk:17-jdk-alpine
    container_name: pedidos-api
    ports:
      - "8080:8080"
    volumes:
      - ./backend/pedidos/pedidos-0.0.1-SNAPSHOT.jar:/app/pedidos-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/app/pedidos-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/pedidosank?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: unless-stopped
    networks:
      - pedidos-network

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/pedidos/browser:/usr/share/nginx/html
    depends_on: [backend]
    networks: 
      - pedidos-network
    restart: unless-stopped

networks:
  pedidos-network:
    driver: bridge

volumes:
  mysql-data: