version: "3.3"

services:
  pedidoapi:
    build:
      context: ./API
    restart: always
    image: rafenex/pedidosback:1.0
    container_name: pedidoback
    networks:
      - compose-bridge
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/pedidosank?allowPublicKeyRetrieval=true
    volumes:
      - pedidoapi_data:/app/data
    depends_on:
      - mysqldb

volumes:
  pedidoapi_data:
