version: "3.3"

networks:
    compose-bridge:
        external: true

services:
  pedidoapi:
    build:
      context: ./API
    restart: always
    image: rafenex/pedidosback:1.0
    container_name: pedidoback
    networks:
      - compose-bridge
    ports:
      - 8081:8080
    volumes:
      - pedidoapi_data:/app/data

volumes:
  pedidoapi_data:
