version: "3.3"

services:
  mysqldb:
    restart: always
    image: mysql:8.0
    container_name: pedidodb
    networks:
      - compose-bridge
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: pedidosank
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
