version: '3.3'

services:
  pedidoapi:
    build: .
    # restart: always
    image: rafenex/pedidosback:1.0
    container_name: pedidoback
    networks:
      - compose-bridge
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment: 
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/pedidosank?allowPublicKeyRetrieval=true   

  mysqldb:
    image: mysql:8.0
    container_name: pedidodb
    networks:
      - compose-bridge
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pedidosank
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  frontend:
    build: ../Front
    container_name: pedidofront
    networks:
      - compose-bridge
    ports:
      - 4200:4200
    depends_on:
      - pedidoapi

networks:
  compose-bridge:
    driver: bridge
